### ISSUE TITLE
errors compiling test library

### ISSUE THREAD

**Issue by magorium** [alb42/AROS-libraries#1]
Hi ALB42,

I've tried to 'make' the test library, using native AROS' gcc, but hat resulted for me into:

``` shell
i386-aros-gcc -O2 -g -fomit-frame-pointer -W -Wall -Wno-parentheses   -c -o lib_header.o lib_header.c
lib_header.c:30:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
lib_header.c:218:41: error: macro "AROS_SLIB_ENTRY" requires 3 arguments, but only 2 given
lib_header.c:218:6: error: 'AROS_SLIB_ENTRY' undeclared here (not in a function)
lib_header.c:219:42: error: macro "AROS_SLIB_ENTRY" requires 3 arguments, but only 2 given
lib_header.c:220:44: error: macro "AROS_SLIB_ENTRY" requires 3 arguments, but only 2 given
lib_header.c:221:45: error: macro "AROS_SLIB_ENTRY" requires 3 arguments, but only 2 given
lib_header.c:222:46: error: macro "AROS_SLIB_ENTRY" requires 3 arguments, but only 2 given
lib_header.c:227:1: error: 'LibExpungeIntern' undeclared here (not in a function)
lib_header.c:227:1: error: initializer element is not constant
make: *** [lib_header.o] Error 1
```

In case it might be unclear, the first error occurs on the following line:

``` c
void *__startup_entries_next;
```

It seems I'm running into that brick wall right from the start :fearful:

On the bright side, ive found a nice small library to port :secret:

**Comment by alb42** [comment]
Thats because they are meant to use with ABIv0 (not on-trunk!!!!) because of the >6 month old bug in the current nightly I can't compile on current ABIv0oT Versions, seems they changed the SDK

**Comment by alb42** [comment]
I could change that to compile on newer Versions.... but then it will not compile on the old ABIv0...
